# Importing Data Set

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv('linux_kernel_git_revlog.csv')
df.head()

,author_timestamp,commit_hash,commit_utc_offset_hours,filename,n_additions,n_deletions,subject,author_id
0,1487807211,f201ebd87652cf1519792f8662bb3f862c76aa33,-8,mm/z3fold.c,7,3,mm/z3fold.c: limit first_num to the actual ran...,0
1,1487807208,083fb8edda0487d192e8c117f625563b920cf7a4,-8,include/linux/pagemap.h,0,1,mm: fix <linux/pagemap.h> stray kernel-doc not...,1
2,1487807205,c87d1655c29500b459fb135258a93f8309ada9c7,-8,Documentation/ABI/obsolete/sysfs-block-zram,0,119,zram: remove obsolete sysfs attrs,2
3,1487807205,c87d1655c29500b459fb135258a93f8309ada9c7,-8,Documentation/ABI/testing/sysfs-block-zram,8,92,zram: remove obsolete sysfs attrs,2
4,1487807205,c87d1655c29500b459fb135258a93f8309ada9c7,-8,Documentation/blockdev/zram.txt,34,39,zram: remove obsolete sysfs attrs,2

In [8]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1429544 entries, 0 to 1429543
Data columns (total 8 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   author_timestamp         1429544 non-null  int64
 1   commit_hash              1429544 non-null  object
 2   commit_utc_offset_hours  1429544 non-null  int64
 3   filename                 1429544 non-null  object
 4   n_additions              1429544 non-null  int64
 5   n_deletions              1429544 non-null  int64
 6   subject                  1429544 non-null  object
 7   author_id                1429544 non-null  int64
dtypes: int64(5), object(3)
memory usage: 87.3+ MB

# Grouping by author_id

In [9]:
count=df['author_id'].value_counts().reset_index()
count.columns = ['author_id', 'Mass']
count=count.sort_values('Mass',ascending=False)
a=count.groupby('author_id').head(1)
print(a)

       author_id   Mass
0           1107  14245
1            730  11995
2             26  11263
3            122  11257
4            467  10565
...          ...    ...
17607       6116      1
17606       6022      1
17605       6026      1
17604       6027      1
21735      21735      1

[21736 rows x 2 columns]

# Selecting a particular Author with highest commits

In [10]:
gdb=(df['author_id']==1107)

In [11]:
ndf=df.loc[gdb,['filename','commit_utc_offset_hours','n_additions','n_deletions','subject','author_timestamp']]
ndf['author_timestamp']=pd.to_datetime(df['author_timestamp'],unit='s')
ndf

,filename,commit_utc_offset_hours,n_additions,n_deletions,subject,author_timestamp
11884,lib/iov_iter.c,-5,31,23,fix a fencepost error in pipe_advance(),2017-01-15 00:33:08
16048,arch/arm64/include/asm/asm-uaccess.h,-5,65,0,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16049,arch/arm64/include/asm/uaccess.h,-5,0,64,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16050,arch/arm64/kernel/entry.S,-5,1,1,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16051,arch/arm64/lib/clear_user.S,-5,1,1,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
...,...,...,...,...,...,...
1408296,net/socket.c,-7,2,1,[PATCH] Fix 32bit sendmsg() flaw,2005-09-08 01:28:51
1409365,drivers/char/Kconfig,-7,1,1,[SPARC64]: Kconfig fix (GEN_RTC dependencies),2005-09-06 06:35:41
1409366,drivers/serial/sunsu.c,-7,7,3,[SUNSU]: Compile fixes.,2005-09-06 06:35:05
1411201,drivers/char/Kconfig,-7,1,1,[SPARC32]: More dependencies fallout,2005-09-02 19:20:18
1411202,drivers/atm/zatm.c,-7,2,2,[ATM]: Fix dereference of uninitialized pointe...,2005-09-02 19:18:03

In [12]:
ndf

,filename,commit_utc_offset_hours,n_additions,n_deletions,subject,author_timestamp
11884,lib/iov_iter.c,-5,31,23,fix a fencepost error in pipe_advance(),2017-01-15 00:33:08
16048,arch/arm64/include/asm/asm-uaccess.h,-5,65,0,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16049,arch/arm64/include/asm/uaccess.h,-5,0,64,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16050,arch/arm64/kernel/entry.S,-5,1,1,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
16051,arch/arm64/lib/clear_user.S,-5,1,1,arm64: don't pull uaccess.h into *.S,2016-12-26 09:10:19
...,...,...,...,...,...,...
1408296,net/socket.c,-7,2,1,[PATCH] Fix 32bit sendmsg() flaw,2005-09-08 01:28:51
1409365,drivers/char/Kconfig,-7,1,1,[SPARC64]: Kconfig fix (GEN_RTC dependencies),2005-09-06 06:35:41
1409366,drivers/serial/sunsu.c,-7,7,3,[SUNSU]: Compile fixes.,2005-09-06 06:35:05
1411201,drivers/char/Kconfig,-7,1,1,[SPARC32]: More dependencies fallout,2005-09-02 19:20:18
1411202,drivers/atm/zatm.c,-7,2,2,[ATM]: Fix dereference of uninitialized pointe...,2005-09-02 19:18:03

# Final DataSet

In [13]:
df = ndf.loc[:,['author_timestamp','n_additions','n_deletions']].copy()
df

           author_timestamp  n_additions  n_deletions
11884   2017-01-15 00:33:08           31           23
16048   2016-12-26 09:10:19           65            0
16049   2016-12-26 09:10:19            0           64
16050   2016-12-26 09:10:19            1            1
16051   2016-12-26 09:10:19            1            1
...                     ...          ...          ...
1408296 2005-09-08 01:28:51            2            1
1409365 2005-09-06 06:35:41            1            1
1409366 2005-09-06 06:35:05            7            3
1411201 2005-09-02 19:20:18            1            1
1411202 2005-09-02 19:18:03            2            2

[14245 rows x 3 columns]